version: "3.7"

services:
  backend:
    build: ./backend
    container_name: flask
    restart: always
    environment:
      - APP_NAME=app
    expose: 
      - 5000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports: 
     - "80:80"
     - "5000:5000"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on: 
     - nginx
    expose:
      - 8080

